### PR TITLE
Ensure ban name is passed to kick if search fails

### LINKED ISSUE #31: Banning someone doesn't always kick them
Checking with ban_record shows they were banned, I then kicked them (which worked). This is 5.4.0-dev

There are no applicable log messages:

```
ACTION[Server]: [sban] Joker-_- banned by rubenwardy reason: hacking
ACTION[Server]: rubenwardy kicks Joker-_-    (this was manually done)
[Server]: [CTF | team] Removing player "Joker-_-"
```

Mods are capture the flag + MT-CTF/rules, MT-CTF/servermods, sauth (d2e0aa834c7c0b6d6000af98eb22088b905441c3), sban (44695d22df6c1fdaeac8213092f1b97a6cb3d534)

### PR DESCRIPTION
**Pull request by shivajiva101**
potentially fixes https://github.com/shivajiva101/sban/issues/31

### CODE REVIEW

File: init.lua [hunk 1]
```diff
@@ -855,6 +855,10 @@ local function create_ban_record(name, source, reason, expires)
 
 	-- kick all player names associated with the id
 	local r = name_records(id)
+	if #r < 1 then -- sanity check for timeout
+		r[1] = {name = name}
+		minetest.log('action', '[sban] named_records search failed!')
```
Comment (rubenwardy) [inline init.lua:860]: should probably be a warning rather than an action?
